FROM python:slim-bullseye
RUN mkdir /app 
COPY requirements.txt /app
WORKDIR /app
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

COPY /src /app/
COPY /src/.config.yml /app/

CMD [ "python3", "main.py" ]
